version: '3'
services:
  node-server:
    build:
      context: ./node-server
    ports:
      - "3080:3080"
    container_name: node-server
    volumes:
       - ./node-server:/usr/src/app/node-server
       - /usr/src/app/node-server/node_modules
  react-ui:
    build:
      context: ./react-ui
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
    volumes:
        - ./react-ui:/usr/src/app/react-ui
        - /usr/src/app/react-ui/node_modules
  postgres-db:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-db:/var/lib/postgresql/data 